### ISSUE TITLE
뒤로가기를 클릭해도 게시물에서 안나가지는 버그

### ISSUE THREAD

**Issue by yjm0313** [hakujitsu7/wakzoo-plus#1]
확률적인지 조건이 있는지는 모르겠지만 게시물을 여러개 보다보면 한번씩 뒤로가기를 눌러도 로딩은 뜨지만 게시물에 머물러 있어요 ㅠㅠ 확인 부탁드립니다 죄송합니다

**Comment by hakujitsu7** [comment]
원인 확인해보고 바로 업데이트 하도록 하겠습니다!! 버그 제보 감사합니다!

**Comment by hakujitsu7** [comment]
문제 원인 파악하였습니다.

새로고침 시 원래 보고 있던 페이지를 유지해주는 기능이 오작동한 것으로 확인되었습니다.

크롬에서는 파이어폭스와 달리 새로고침을 한다고 무조건 webNavigation reload 이벤트가 발생하는 게 아니라 컨트롤 F5, 컨트롤 쉬프트 R 등을 눌러 새로고침을 할 때만 reload 이벤트가 발생한다는 차이점이 있습니다.
이 때문에 1.1 버전 업데이트 당시 F5만 눌러서 새로고침할 때에도 페이지 유지 기능이 정상작동하게 만들고자, auto_subframe 이벤트까지도 새로고침 이벤트로 감지하게 하였습니다.

문제는 뒤로가기에서도 auto_subframe 이벤트가 발생하여, 확장 프로그램이 새로고침 이벤트가 발생한 것으로 오인하고 탭을 뒤로가기 이전 위치로 되돌려버리네요...

현재 해당 문제에 대해 기능을 임시적으로 비활성화하는 핫픽스 버전을 웹 스토어에 등록 요청한 상태이며, 일반적으로 등록까지 1일~2일 정도의 시간이 소요됩니다.

만약 그보다 이전에 핫픽스 사용이 필요하신 경우, 아래 링크에서 수동 설치해 주시면 감사하겠습니다.
https://github.com/hakujitsu7/wakzoo-plus/releases/tag/1.2

급하게 업데이트를 올리느라 충분한 테스트가 이루어지지 않아 발생한 문제이고, 제 잘못임이 너무나 분명한 상황입니다 ㅜㅜ
앞으로는 동일한 문제 만들지 않도록 충분한 테스트 과정 뒤에 업데이트를 배포하도록 하겠습니다...

뒤늦게라도 대응할 수 있도록 버그 제보해주셔신 점 깊은 감사를 표하며,
불편함 느끼셨을 사용자 분들께 다시 한번 진심으로 죄송합니다.

**Comment by hakujitsu7** [comment]
현재 해당 기능을 임시적으로 비활성화한 핫픽스 버전(1.2)이 크롬 웹 스토어에 정식 등록된 상태입니다.

자동 업데이트가 되긴 하지만, 이게 업데이트 올라오자마자 바로 되는 그런 구조는 아닙니다.
그래서 아직 1.1 버전 사용 중인 분들께선 직접 크롬 웹 스토어에서 1.2 버전을 다시 설치해 주시면 감사하겠습니다.

불편을 드려 진심으로 죄송합니다. ㅜㅜ

**Comment by yjm0313** [comment]
빠른 피드백수용 감사합니다 ㅠㅠ

2022년 3월 9일 (수) 오후 11:33, Shin Jinhyeok ***@***.***>님이 작성:
